# railway.toml

[build]
  command = "npm install --omit=dev && npm run build" # Comando para construir sua aplicação

[deploy]
  command = "npm start" # Comando para iniciar sua aplicação

[env]
  PORT = "3001" # Definindo a porta que sua aplicação usará
  NODE_ENV = "production" # Definindo o ambiente como produção